


-- Test the add_numbers function
BEGIN;

    CREATE EXTENSION IF NOT EXISTS pgtap;
    CREATE EXTENSION IF NOT EXISTS unaccent;
    CREATE EXTENSION IF NOT EXISTS tsp_semantic_headline;

    SELECT plan(6);

    -- Test Case 1: 2 + 3 should equal 5

    CREATE TEMP TABLE _files(content text) ON COMMIT DROP;

    INSERT INTO _files VALUES ('Alles ward wieder ruhig. Die Köpfe versanken in den Heften, und der Neuling verharrte zwei Stunden lang in musterhafter Haltung, obgleich ihm von Zeit zu Zeit mit einem Federhalter abgeschwuppte kleine Papierkugeln ins Gesicht flogen. Er wischte sich jedesmal mit der Hand ab, ohne sich weiter zu bewegen noch die Augen aufzuschlagen.
        Abends, im Arbeitssaal, holte er seine Ärmelschoner aus seinem Pult, brachte seine Habseligkeiten in Ordnung und liniierte sich sorgsam sein Schreibpapier. Die andern beobachteten, wie er gewissenhaft arbeitete; er schlug alle Wörter im Wörterbuche nach und gab sich viel Mühe. Zweifellos verdankte er es dem großen Fleiße, den er an den Tag legte, daß man ihn nicht in der Quinta zurückbehielt; denn wenn er auch die Regeln ganz leidlich wußte, so verstand er sich doch nicht gewandt auszudrücken. Der Pfarrer seines Heimatdorfes hatte ihm kaum ein bißchen Latein beigebracht, und aus Sparsamkeit war er von seinen Eltern so spät wie nur möglich auf das Gymnasium geschickt worden.
        Sein Vater, Karl Dionys Barthel Bovary, war Stabsarzt a.D.; er hatte sich um 1812 bei den Aushebungen etwas zuschulden kommen lassen, worauf er den Abschied nehmen mußte. Er setzte nunmehr seine körperlichen Vorzüge in bare Münze um und ergatterte sich im Handumdrehen eine Mitgift von sechzigtausend Franken, die ihm in der Person der Tochter eines Hutfabrikanten in den Weg kam. Das Mädchen hatte sich in den hübschen Mann verliebt. Er war ein Schwerenöter und Prahlhans, der sporenklingend einherstolzierte, Schnurr- und Backenbart trug, die Hände voller Ringe hatte und in seiner Kleidung auffällige Farben liebte. Neben seinem Haudegentum besaß er das gewandte Getue eines Ellenreiters. Sobald er verheiratet war, begann er zwei, drei Jahre auf Kosten seiner Frau zu leben, aß und trank gut, schlief bis in den halben Tag hinein und rauchte aus langen Porzellanpfeifen. Nachts pflegte er sehr spät heimzukommen, nachdem er sich in Kaffeehäusern herumgetrieben hatte. Als sein Schwiegervater starb und nur wenig hinterließ, war Bovary empört darüber. Er übernahm die Fabrik, büßte aber Geld dabei ein, und so zog er sich schließlich auf das Land zurück, wovon er sich goldne Berge erträumte. Aber er verstand von der Landwirtschaft auch nicht mehr als von der Hutmacherei, ritt lieber spazieren, als daß er seine Pferde zur Arbeit einspannen ließ, trank seinen Apfelwein flaschenweise selber, anstatt ihn in Fässern zu verkaufen, ließ das fetteste Geflügel in den eignen Magen gelangen und schmierte sich mit dem Speck seiner Schweine seine Jagdstiefel. Auf diesem Wege sah er zu guter Letzt ein, daß es am tunlichsten für ihn sei, sich in keinerlei Geschäfte mehr einzulassen.
        Für zweihundert Franken Jahrespacht mietete er nun in einem Dorfe im Grenzgebiete von Caux und der Pikardie ein Grundstück, halb Bauernhof, halb Herrenhaus. Dahin zog er sich zurück, fünfundvierzig Jahre alt, mit Gott und der Welt zerfallen, gallig und mißgünstig zu jedermann. Von den Menschen angeekelt, wie er sagte, wollte er in Frieden für sich hinleben.
        Seine Frau war dereinst toll verliebt in ihn gewesen. Aber unter tausend Demütigungen starb ihre Liebe doch rettungslos. Ehedem heiter, mitteilsam und herzlich, war sie allmählich (just wie sich abgestandner Wein zu Essig wandelt) mürrisch, zänkisch und nervös geworden. Ohne zu klagen, hatte sie viel gelitten, wenn sie immer wieder sah, wie ihr Mann hinter allen Dorfdirnen her war und abends müde und nach Fusel stinkend aus irgendwelcher Spelunke zu ihr nach Haus kam. Ihr Stolz hatte sich zunächst mächtig geregt, aber schließlich schwieg sie, würgte ihren Grimm in stummem Stoizismus hinunter und beherrschte sich bis zu ihrem letzten Stündlein. Sie war unablässig tätig und immer auf dem Posten. Sie war es, die zu den Anwälten und Behörden ging. Sie wußte, wenn Wechsel fällig waren; sie erwirkte ihre Verlängerung. Sie machte alle Hausarbeiten, nähte, wusch, beaufsichtigte die Arbeiter und führte die Bücher, während der Herr und Gebieter sich um nichts kümmerte, aus seinem Zustande griesgrämlicher Schläfrigkeit nicht herauskam und sich höchstens dazu ermannte, seiner Frau garstige Dinge zu sagen. Meist hockte er am Kamin, qualmte und spuckte ab und zu in die Asche.
        Als ein Kind zur Welt kam, mußte es einer Amme gegeben werden; und als es wieder zu Hause war, wurde das schwächliche Geschöpf grenzenlos verwöhnt. Die Mutter nährte es mit Zuckerzeug. Der Vater ließ es barfuß herumlaufen und meinte höchst weise obendrein, der Kleine könne eigentlich ganz nackt gehen wie die Jungen der Tiere. Im Gegensatz zu den Bestrebungen der Mutter hatte er sich ein bestimmtes männliches Erziehungsideal in den Kopf gesetzt, nach welchem er seinen Sohn zu modeln sich Mühe gab. Er sollte rauh angefaßt werden wie ein junger Spartaner, damit er sich tüchtig abhärte. Er mußte in einem ungeheizten Zimmer schlafen, einen ordentlichen Schluck Rum vertragen und auf den „kirchlichen Klimbim“ schimpfen. Aber der Kleine war von friedfertiger Natur und widerstrebte allen diesen Bemühungen. Die Mutter schleppte ihn immer mit sich herum. Sie schnitt ihm Pappfiguren aus und erzählte ihm Märchen; sie unterhielt sich mit ihm in endlosen Selbstgesprächen, die von schwermütiger Fröhlichkeit und wortreicher Zärtlichkeit überquollen. In ihrer Verlassenheit pflanzte sie in das Herz ihres Jungen alle ihre eigenen unerfüllten und verlorenen Sehnsüchte. Im Traume sah sie ihn erwachsen, hochangesehen, schön, klug, als Beamten beim Straßen- und Brückenbau oder in einer Ratsstellung. Sie lehrte ihn Lesen und brachte ihm sogar an dem alten Klavier, das sie besaß, das Singen von ein paar Liedchen bei. Ihr Mann, der von gelehrten Dingen nicht viel hielt, bemerkte zu alledem, es sei bloß schade um die Mühe; sie hätten doch niemals die Mittel, den Jungen auf eine höhere Schule zu schicken oder ihm ein Amt oder ein Geschäft zu kaufen. Zu was auch? Dem Kecken gehöre die Welt! Frau Bovary schwieg still, und der Kleine trieb sich im Dorfe herum. Er lief mit den Feldarbeitern hinaus, scheuchte die Krähen auf, schmauste Beeren an den Rainen, hütete mit einer Gerte die Truthähne und durchstreifte Wald und Flur. Wenn es regnete, spielte er unter dem Kirchenportal mit kleinen Steinchen, und an den Feiertagen bestürmte er den Kirchendiener, die Glocken läuten zu dürfen. Dann hängte er sich mit seinem ganzen Gewicht an den Strang der großen Glocke und ließ sich mit emporziehen. So wuchs er auf wie eine Lilie auf dem Felde, bekam kräftige Glieder und frische Farben.
        Als er zwölf Jahre alt geworden war, setzte es seine Mutter durch, daß er endlich etwas Gescheites lerne. Er bekam Unterricht beim Pfarrer, aber die Stunden waren so kurz und so unregelmäßig, daß sie nicht viel Erfolg hatten. Sie fanden statt, wenn der Geistliche einmal gar nichts anders zu tun hatte, in der Sakristei, im Stehen, in aller Hast in den Pausen zwischen den Taufen und Begräbnissen. Mitunter, wenn er keine Lust hatte auszugehen, ließ der Pfarrer seinen Schüler nach dem Ave-Maria zu sich holen. Die beiden saßen dann oben im Stübchen. Mücken und Nachtfalter tanzten um die Kerze; aber es war so warm drin, daß der Junge schläfrig wurde, und es dauerte nicht lange, da schnarchte der biedere Pfarrer, die Hände über dem Schmerbauche gefaltet. Es kam auch vor, daß der Seelensorger auf dem Heimwege von irgendeinem Kranken in der Umgegend, dem er das Abendmahl gereicht hatte, den kleinen Vagabunden im Freien erwischte; dann rief er ihn heran, hielt ihm eine viertelstündige Strafpredigt und benutzte die Gelegenheit, ihn im Schatten eines Baumes seine Lektion hersagen zu lassen. Entweder war es der Regen, der den Unterricht störte, oder irgendein Bekannter, der vorüberging. Übrigens war der Lehrer durchweg mit seinem Schüler zufrieden, ja er meinte sogar, der „junge Mann“ habe ein gar treffliches Gedächtnis.
        So konnte es nicht weitergehen. Frau Bovary ward energisch, und ihr Mann gab widerstandslos nach, vielleicht weil er sich selber schämte, wahrscheinlicher aber aus Ohnmacht. Man wollte nur noch ein Jahr warten; der Junge sollte erst gefirmelt werden.
        Darüber hinaus verstrich abermals ein halbes Jahr, dann aber wurde Karl wirklich auf das Gymnasium nach Rouen geschickt. Sein Vater brachte ihn selber hin. Das war Ende Oktober.
        Die meisten seiner damaligen Kameraden werden sich kaum noch deutlich an ihn erinnern. Er war ein ziemlich phlegmatischer Junge, der in der Freizeit wie ein Kind spielte, in den Arbeitsstunden eifrig lernte, während des Unterrichts aufmerksam dasaß, im Schlafsaal vorschriftsmäßig schlief und bei den Mahlzeiten ordentlich zulangte. Sein Verkehr außerhalb der Schule war ein Eisengroßhändler in der Handschuhmachergasse, der aller vier Wochen einmal mit ihm ausging, an Sonntagen nach Ladenschluß. Er lief mit ihm am Hafen spazieren, zeigte ihm die Schiffe und brachte ihn abends um sieben Uhr vor dem Abendessen wieder in das Gymnasium. Jeden Donnerstag abend schrieb Karl mit roter Tinte an seine Mutter einen langen Brief, den er immer mit drei Oblaten zuklebte. Hernach vertiefte er sich wieder in seine Geschichtshefte, oder er las in einem alten Exemplar von Barthelemys „Reise des jungen Anacharsis“, das im Arbeitssaal herumlag. Bei Ausflügen plauderte er mit dem Pedell, der ebenfalls vom Lande war.
        Durch seinen Fleiß gelang es ihm, sich immer in der Mitte der Klasse zu halten; einmal errang er sich sogar einen Preis in der Naturkunde. Aber gegen Ende des dritten Schuljahres nahmen ihn seine Eltern vom Gymnasium fort und ließen ihn Medizin studieren. Sie waren der festen Zuversicht, daß er sich bis zum Staatsexamen schon durchwürgen würde.
        Die Mutter mietete ihm ein Stübchen, vier Stock hoch, nach der Eau-de-Robec zu gelegen, im Hause eines Färbers, eines alten Bekannten von ihr. Sie traf Vereinbarungen über die Verpflegung ihres Sohnes, besorgte ein paar Möbelstücke, einen Tisch und zwei Stühle, wozu sie von zu Hause noch eine Bettstelle aus Kirschbaumholz kommen ließ. Des weiteren kaufte sie ein Kanonenöfchen und einen kleinen Vorrat von Holz, damit ihr armer Junge nicht frieren sollte. Acht Tage darnach reiste sie wieder heim, nachdem sie ihn tausend- und abertausendmal ermahnt hatte, ja hübsch fleißig und solid zu bleiben, sintemal er nun ganz allein auf sich selbst angewiesen sei.
        Vor dem Verzeichnis der Vorlesungen auf dem schwarzen Brette der medizinischen Hochschule vergingen dem neubackenen Studenten Augen und Ohren. Er las da von anatomischen und pathologischen Kursen, von Kollegien über Physiologie, Pharmazie, Chemie, Botanik, Therapeutik und Hygiene, von Kursen in der Klinik, von praktischen Übungen usw. Alle diese vielen Namen, über deren Herkunft er sich nicht einmal klar war, standen so recht vor ihm wie geheimnisvolle Pforten in das Heiligtum der Wissenschaft.
        Er lernte gar nichts. So aufmerksam er auch in den Vorlesungen war, er begriff nichts. Um so mehr büffelte er. Er schrieb fleißig nach, versäumte kein Kolleg und fehlte in keiner Übung. Er erfüllte sein tägliches Arbeitspensum wie ein Gaul im Hippodrom, der in einem fort den Hufschlag hintrottet, ohne zu wissen, was für ein Geschäft er eigentlich verrichtet.
        Zu seiner pekuniären Unterstützung schickte ihm seine Mutter allwöchentlich durch den Botenmann ein Stück Kalbsbraten. Das war sein Frühstück, wenn er aus dem Krankenhause auf einen Husch nach Hause kam. Sich erst hinzusetzen, dazu langte die Zeit nicht, denn er mußte alsbald wieder in ein Kolleg oder zur Anatomie oder Klinik eilen, durch eine Unmenge von Straßen hindurch. Abends nahm er an der kargen Hauptmahlzeit seiner Wirtsleute teil. Hinterher ging er hinauf in seine Stube und setzte sich an seine Lehrbücher, oft in nassen Kleidern, die ihm dann am Leibe bei der Rotglut des kleinen Ofens zu dampfen begannen.
        An schönen Sommerabenden, wenn die schwülen Gassen leer wurden und die Dienstmädchen vor den Haustüren Ball spielten, öffnete er sein Fenster und sah hinaus. Unten floß der Fluß vorüber, der aus diesem Viertel von Rouen ein häßliches Klein-Venedig machte. Seine gelben, violett und blau schimmernden Wasser krochen träg zu den Wehren und Brücken. Arbeiter kauerten am Ufer und wuschen sich die Arme in der Flut. An Stangen, die aus Speichergiebeln lang hervorragten, trockneten Bündel von Baumwolle in der Luft. Gegenüber, hinter den Dächern, leuchtete der weite klare Himmel mit der sinkenden roten Sonne. Wie herrlich mußte es da draußen im Freien sein! Und dort im Buchenwald wie frisch! Karl holte tief Atem, um den köstlichen Duft der Felder einzusaugen, der doch gar nicht bis zu ihm drang.
        Er magerte ab und sah sehr schmächtig aus. Sein Gesicht bekam einen leidvollen Zug, der es beinahe interessant machte. Er ward träge, was gar nicht zu verwundern war, und seinen guten Vorsätzen mehr und mehr untreu. Heute versäumte er die Klinik, morgen ein Kolleg, und allmählich fand er Genuß am Faulenzen und ging gar nicht mehr hin. Er wurde Stammgast in einer Winkelkneipe und ein passionierter Dominospieler. Alle Abende in einer schmutzigen Spelunke zu hocken und mit den beinernen Spielsteinen auf einem Marmortische zu klappern, das dünkte ihn der höchste Grad von Freiheit zu sein, und das stärkte ihm sein Selbstbewußtsein. Es war ihm das so etwas wie der Anfang eines weltmännischen Lebens, dieses Kosten verbotener Freuden. Wenn er hinkam, legte er seine Hand mit geradezu sinnlichem Vergnügen auf die Türklinke. Eine Menge Dinge, die bis dahin in ihm unterdrückt worden waren, gewannen nunmehr Leben und Gestalt. Er lernte Gassenhauer auswendig, die er gelegentlich zum besten gab. Béranger, der Freiheitssänger, begeisterte ihn. Er lernte eine gute Bowle brauen, und zu guter Letzt entdeckte er die Liebe. Dank diesen Vorbereitungen fiel er im medizinischen Staatsexamen glänzend durch.
        Man erwartete ihn am nämlichen Abend zu Haus, wo sein Erfolg bei einem Schmaus gefeiert werden sollte. Er machte sich zu Fuß auf den Weg und erreichte gegen Abend seine Heimat. Dort ließ er seine Mutter an den Dorfeingang bitten und beichtete ihr alles. Sie entschuldigte ihn, schob den Mißerfolg der Ungerechtigkeit der Examinatoren in die Schuhe und richtete ihn ein wenig auf, indem sie ihm versprach, die Sache ins Lot zu bringen. Erst volle fünf Jahre darnach erfuhr Herr Bovary die Wahrheit. Da war die Geschichte verjährt, und so fügte er sich drein. Übrigens hätte er es niemals zugegeben, daß sein leiblicher Sohn ein Dummkopf sei.
        Karl widmete sich von neuem seinem Studium und bereitete sich hartnäckigst auf eine nochmalige Prüfung vor. Alles, was er gefragt werden konnte, lernte er einfach auswendig. In der Tat bestand er das Examen nunmehr mit einer ziemlich guten Note. Seine Mutter erlebte einen Freudentag. Es fand ein großes Festmahl statt.
        Wo sollte er seine ärztliche Praxis nun ausüben? In Tostes. Dort gab es nur einen und zwar sehr alten Arzt. Mutter Bovary wartete schon lange auf sein Hinscheiden, und kaum hatte der alte Herr das Zeitliche gesegnet, da ließ sich Karl Bovary auch bereits als sein Nachfolger daselbst nieder.
        Aber nicht genug, daß die Mutter ihren Sohn erzogen, ihn Medizin studieren lassen und ihm eine Praxis ausfindig gemacht hatte: nun mußte er auch eine Frau haben. Selbige fand sie in der Witwe des Gerichtsvollziehers von Dieppe, die neben fünfundvierzig Jährlein zwölfhundert Franken Rente ihr eigen nannte. Obgleich sie häßlich war, dürr wie eine Hopfenstange und im Gesicht so viel Pickel wie ein Kirschbaum Blüten hatte, fehlte es der Witwe Dubuc keineswegs an Bewerbern. Um zu ihrem Ziele zu gelangen, mußte Mutter Bovary erst alle diese Nebenbuhler aus dem Felde schlagen, was sie sehr geschickt fertig brachte. Sie triumphierte sogar über einen Fleischermeister, dessen Anwartschaft durch die Geistlichkeit unterstützt wurde.
        Karl hatte in die Heirat eingewilligt in der Erwartung, sich dadurch günstiger zu stellen. Er hoffte, persönlich wie pekuniär unabhängiger zu werden. Aber Heloise nahm die Zügel in ihre Hände. Sie drillte ihm ein, was er vor den Leuten zu sagen habe und was nicht. Alle Freitage wurde gefastet. Er durfte sich nur nach ihrem Geschmacke kleiden, und die Patienten, die nicht bezahlten, mußte er auf ihren Befehl hin kujonieren. Sie erbrach seine Briefe, überwachte jeden Schritt, den er tat, und horchte an der Türe, wenn weibliche Wesen in seiner Sprechstunde waren. Jeden Morgen mußte sie ihre Schokolade haben, und die Rücksichten, die sie erheischte, nahmen kein Ende. Unaufhörlich klagte sie über Migräne, Brustschmerzen oder Verdauungsstörungen. Wenn viel Leute durch den Hausflur liefen, ging es ihr auf die Nerven. War Karl auswärts, dann fand sie die Einsamkeit gräßlich; kehrte er heim, so war es zweifellos bloß, weil er gedacht habe, sie liege im Sterben. Wenn er nachts in das Schlafzimmer kam, streckte sie ihm ihre mageren langen Arme aus ihren Decken entgegen, umschlang seinen Hals und zog ihn auf den Rand ihres Bettes. Und nun ging die Jeremiade los. Er vernachlässige sie, er liebe eine andre! Man habe es ihr ja gleich gesagt, diese Heirat sei ihr Unglück. Schließlich bat sie ihn um einen Löffel Arznei, damit sie gesund werde, und um ein bißchen mehr Liebe.
        Zweites Kapitel 
        Einmal nachts gegen elf Uhr wurde das Ehepaar durch das Getrappel eines Pferdes geweckt, das gerade vor der Haustüre zum Stehen kam. Anastasia, das Dienstmädchen, klappte ihr Bodenfenster auf und verhandelte eine Weile mit einem Manne, der unten auf der Straße stand. Er wolle den Arzt holen. Er habe einen Brief an ihn.
        Anastasia stieg frierend die Treppen hinunter und schob die Riegel auf, einen und dann den andern. Der Bote ließ sein Pferd stehen, folgte dem Mädchen und betrat ohne weiteres das Schlafgemach. Er entnahm seinem wollnen Käppi, an dem eine graue Troddel hing, einen Brief, der in einen Lappen eingewickelt war, und überreicht ihn dem Arzt mit höflicher Gebärde. Der richtete sich im Bett auf, um den Brief zu lesen. Anastasia stand dicht daneben und hielt den Leuchter. Die Frau Doktor kehrte sich verschämt der Wand zu und zeigte den Rücken.
        In dem Briefe, den ein niedliches blaues Siegel verschloß, wurde Herr Bovary dringend gebeten, unverzüglich nach dem Pachtgut Les Bertaux zu kommen, ein gebrochenes Bein zu behandeln. Nun braucht man von Tostes über Longueville und Sankt Victor bis Bertaux zu Fuß sechs gute Stunden. Die Nacht war stockfinster. Frau Bovary sprach die Befürchtung aus, es könne ihrem Manne etwas zustoßen. Infolgedessen ward beschlossen, daß der Stallknecht vorausreiten, Karl aber erst drei Stunden später, nach Mondaufgang, folgen solle. Man würde ihm einen Jungen entgegenschicken, der ihm den Weg zum Gute zeige und ihm den Hof aufschlösse.
        Früh gegen vier Uhr machte sich Karl, fest in feinen Mantel gehüllt, auf den Weg nach Bertaux. Noch ganz verschlafen überließ er sich dem Zotteltrab seines Gaules. Wenn dieser von selber vor irgendeinem im Wege liegenden Hindernis zum Halten parierte, wurde der Reiter jedesmal wach, erinnerte sich des gebrochnen Beines und begann in seinem Gedächtnisse alles auszukramen, was er von Knochenbrüchen wußte.
        Der Regen hörte auf. Es dämmerte. Auf den laublosen Ästen der Apfelbäume hockten regungslose Vögel, das Gefieder ob des kühlen Morgenwindes gesträubt. So weit das Auge sah, dehnte sich flaches Land. Auf dieser endlosen grauen Fläche hoben sich hie und da in großen Zwischenräumen tiefviolette Flecken ab, die am Horizonte mit des Himmels trüben Farben zusammenflossen; das waren Baumgruppen um Güter und Meiereien herum. Von Zeit zu Zeit riß Karl seine Augen auf, bis ihn die Müdigkeit von neuem überwältigte und der Schlaf von selber wiederkam. Er geriet in einen traumartigen Zustand, in dem sich frische Empfindungen mit alten Erinnerungen paarten, so daß er ein Doppelleben führte. Er war noch Student und gleichzeitig schon Arzt und Ehemann. Im nämlichen Moment glaubte er in seinem Ehebette zu liegen und wie einst durch den Operationssaal zu schreiten. Der Geruch von heißen Umschlägen mischte sich in seiner Phantasie mit dem frischen Dufte des Morgentaus. Dazu hörte er, wie die Messingringe an den Stangen der Bettvorhänge klirrten und wie seine Frau im Schlafe atmete ...
        Als er durch das Dorf Vassonville ritt, bemerkte er einen Jungen, der am Rande des Straßengrabens im Grase saß.
        „Sind Sie der Herr Doktor?“
        Als Karl diese Frage bejahte, nahm der Kleine seine Holzpantoffeln in die Hände und begann vor dem Pferde herzurennen. Unterwegs hörte Bovary aus den Reden seines Führers heraus, daß Herr Rouault, der Patient, der ihn erwartete, einer der wohlhabendsten Landwirte sei. Er hatte sich am vergangenen Abend auf dem Heimwege von einem Nachbar, wo man das Dreikönigsfest gefeiert hatte, ein Bein gebrochen. Seine Frau war schon zwei Jahre tot. Er lebte ganz allein mit „dem gnädigen Fräulein“, das ihm den Haushalt führte.
        Die Radfurchen wurden tiefer. Man näherte sich dem Gute. Plötzlich verschwand der Junge in der Lücke einer Gartenhecke, um hinter der Mauer eines Vorhofes wieder aufzutauchen, wo er ein großes Tor öffnete. Das Pferd trat in nasses rutschiges Gras, und Karl mußte sich ducken, um nicht vom Baumgezweig aus dem Sattel gerissen zu werden. Hofhunde fuhren aus ihren Hütten, schlugen an und rasselten an den Ketten. Als der Arzt in den eigentlichen Gutshof einritt, scheute der Gaul und machte einen großen Satz zur Seite.   
        Das Pachtgut Bertaux war ein ansehnliches Besitztum. Durch die offenstehenden Türen konnte man in die Ställe blicken, wo kräftige Ackergäule gemächlich aus blanken Raufen ihr Heu kauten. Längs der Wirtschaftsgebäude zog sich ein dampfender Misthaufen hin. Unter den Hühnern und Truthähnen machten sich fünf bis sechs Pfauen mausig, der Stolz der Güter jener Gegend. Der Schafstall war lang, die Scheune hoch und ihre Mauern spiegelglatt. Im Schuppen standen zwei große Leiterwagen und vier Pflüge, dazu die nötigen Pferdegeschirre, Kumte und Peitschen; auf den blauen Woilachs aus Schafwolle hatte sich feiner Staub gelagert, der von den Kornböden heruntersickerte. Der Hof, der nach dem Wohnhause zu etwas anstieg, war auf beiden Seiten mit einer Reihe Bäume bepflanzt. Vom Tümpel her erscholl das fröhliche Geschnatter der Gänse.
        An der Schwelle des Hauses erschien ein junges Frauenzimmer in einem mit drei Volants besetzten blauen Merinokleide und begrüßte den Arzt. Er wurde nach der Küche geführt, wo ein tüchtiges Feuer brannte. Auf dem Herde kochte in kleinen Töpfen von verschiedener Form das Frühstück des Gesindes. Oben im Rauchfang hingen naßgewordene Kleidungsstücke zum Trocknen. Kohlenschaufel, Feuerzange und Blasebalg, alle miteinander von riesiger Größe, funkelten wie von blankem Stahl, während längs der Wände eine Unmenge Küchengerät hing, über dem die helle Herdflamme um die Wette mit den ersten Strahlen der durch die Fenster huschenden Morgensonne spielte und glitzerte.
        Karl stieg in den ersten Stock hinauf, um den Kranken aufzusuchen. Er fand ihn in seinem Bett, schwitzend unter seinen Decken. Seine Nachtmütze hatte er in die Stube geschleudert. Es war ein stämmiger kleiner Mann, ein Fünfziger, mit weißem Haar, blauen Augen und kahler Stirn. Er trug Ohrringe. Neben ihm auf einem Stuhle stand eine große Karaffe voll Branntwein, aus der er sich von Zeit zu Zeit ein Gläschen einschenkte, um „Mumm in die Knochen zu kriegen“. Angesichts des Arztes legte sich seine Erregung. Statt zu fluchen und zu wettern — was er seit zwölf Stunden getan hatte — fing er nunmehr an zu ächzen und zu stöhnen.
        Der Bruch war einfach, ohne jedwede Komplikation. Karl hätte sich einen leichteren Fall nicht zu wünschen gewagt. Alsbald erinnerte er sich der Allüren, die seine Lehrmeister an den Krankenlagern zur Schau getragen harten, und spendete dem Patienten ein reichliches Maß der üblichen guten Worte, jenes Chirurgenbalsams, der an das Öl gemahnt, mit dem die Seziermesser eingefettet werden. Er ließ sich aus dem Holzschuppen ein paar Latten holen, um Holz zu Schienen zu bekommen. Von den gebrachten Stücken wählte er eins aus, schnitt die Schienen daraus zurecht und glättete sie mit einer Glasscherbe. Währenddem stellte die Magd Leinwandbinden her, und Fräulein Emma, die Tochter des Hauses, versuchte Polster anzufertigen. Als sie ihren Nähkasten nicht gleich fand, polterte der Vater los. Sie sagte kein Wort. Aber beim Nähen stach sie sich in den Finger, nahm ihn in den Mund und sog das Blut aus.
        Karl war erstaunt, was für blendendweiße Nägel sie hatte. Sie waren mandelförmig geschnitten und sorglich gepflegt, und so schimmerten sie wie das feinste Elfenbein. Ihre Hände freilich waren nicht gerade schön, vielleicht nicht weiß genug und ein wenig zu mager in den Fingern; dabei waren sie allzu schlank, nicht besonders weich und in ihren Linien ungraziös. Was jedoch schön an ihr war, das waren ihre Augen. Sie waren braun, aber im Schatten der Wimpern sahen sie schwarz aus, und ihr offener Blick traf die Menschen mit der Kühnheit der Unschuld.
        Als der Verband fertig war, lud Herr Rouault den Arzt feierlich „einen Bissen zu essen“, ehe er wieder aufbräche. Karl ward in das Eßzimmer geführt, das zu ebener Erde lag. Auf einem kleinen Tische war für zwei Personen gedeckt; neben den Gedecken blinkten silberne Becher. Aus dem großen Eichenschranke, gegenüber dem Fenster, strömte Geruch von Iris und feuchtem Leinen. In einer Ecke standen aufrecht in Reih und Glied mehrere Säcke mit Getreide; sie hatten auf der Kornkammer nebenan keinen Platz gefunden, zu der drei Steinstufen hinaufführten. In der Mitte der Wand, deren grüner Anstrich sich stellenweise abblätterte, hing in einem vergoldeten Rahmen eine Bleistiftzeichnung: der Kopf einer Minerva. In schnörkeliger Schrift stand darunter geschrieben. „Meinem lieben Vater!“
        Sie sprachen zuerst von dem Unfall, dann vom Wetter, vom starken Frost, von den Wölfen, die nachts die Umgegend unsicher machen. Fräulein Rouault schwärmte gar nicht besonders von dem Leben auf dem Lande, zumal jetzt nicht, wo die ganze Last der Gutswirtschaft fast allein auf ihr ruhe. Da es im Zimmer kalt war, fröstelte sie während der ganzen Mahlzeit. Beim Essen fielen ihre vollen Lippen etwas auf. Wenn das Gespräch stockte, pflegte sie mit den Oberzähnen auf die Unterlippe zu beißen.
        Ihr Hals wuchs aus einem weißen Umlegekragen heraus. Ihr schwarzes, hinten zu einem reichen Knoten vereintes Haar war in der Mitte gescheitelt; beide Hälften lagen so glatt auf dem Kopfe, daß sie wie zwei Flügel aus je einem Stücke aussahen und kaum die Ohrläppchen blicken ließen. Über den Schläfen war das Haar gewellt, was der Landarzt noch nie in seinem Leben gesehen hatte. Ihre Wangen waren rosig. Zwischen zwei Knöpfen ihrer Taille lugte — wie bei einem Herrn — ein Lorgnon aus Schildpatt hervor.
        Nachdem sich Karl oben beim alten Rouault verabschiedet hatte, trat er nochmals in das Eßzimmer. Er fand Emma am Fenster stehend, die Stirn an die Scheiben gedrückt. Sie schaute in den Garten hinaus, wo der Wind die Bohnenstangen umgeworfen hatte. Sich umwendend, fragte sie:
        „Suchen Sie etwas?“
        „Meinen Reitstock, wenn Sie gestatten!“
        Er fing an zu suchen, hinter den Türen und unter den Stühlen. Der Stock war auf den Fußboden gefallen, gerade zwischen die Säcke und die Wand. Emma entdeckte ihn. Als sie sich über die Säcke beugte, wollte Karl ihr galant zuvorkommen. Wie er seinen Arm in der nämlichen Absicht wie sie ausstreckte, berührte seine Brust den gebückten Rücken des jungen Mädchens. Sie fühlten es beide. Emma fuhr rasch in die Höhe. Ganz rot geworden, sah sie ihn über die Schulter weg an, indem sie ihm seinen Reitstock reichte.
        Er hatte versprochen, in drei Tagen wieder nachzusehen; statt dessen war er bereits am nächsten Tag zur Stelle, und von da ab kam er regelmäßig zweimal in der Woche, ungerechnet die gelegentlichen Besuche, die er hin und wieder machte, wenn er „zufällig in der Gegend“ war. Übrigens ging alles vorzüglich; die Heilung verlief regelrecht, und als man nach sechs und einer halben Woche Vater Rouault ohne Stock wieder in Haus und Hof herumstiefeln sah, hatte sich Bovary in der ganzen Gegend den Ruf einer Kapazität erworben. Der alte Herr meinte, besser hätten ihn die ersten Ärzte von Yvetot oder selbst von Rouen auch nicht kurieren können.
        Karl dachte gar nicht daran, sich zu befragen, warum er so gern nach dem Rouaultschen Gute kam. Und wenn er auch darüber nachgesonnen hätte, so würde er den Beweggrund seines Eifers zweifellos in die Wichtigkeit des Falles oder vielleicht in das in Aussicht stehende hohe Honorar gelegt haben. Waren dies aber wirklich die Gründe, die ihm seine Besuche des Pachthofes zu köstlichen Abwechselungen in dem armseligen Einerlei seines tätigen Lebens machten? An solchen Tagen stand er zeitig auf, ritt im Galopp ab und ließ den Gaul die ganze Strecke lang kaum zu Atem kommen. Kurz vor seinem Ziele aber pflegte er abzusitzen und sich die Stiefel mit Gras zu reinigen; dann zog er sich die braunen Reithandschuhe an, und so ritt er kreuzvergnügt in den Gutshof ein. Es war ihm ein Wonnegefühl, mit der Schulter gegen den nachgebenden Flügel des Hoftores anzureiten, den Hahn auf der Mauer krähen zu hören und sich von der Dorfjugend umringt zu sehen. Er liebte die Scheune und die Ställe; er liebte den Papa Rouault, der ihm so treuherzig die Hand schüttelte und ihn seinen Lebensretter nannte; er liebte die niedlichen Holzpantoffeln des Gutsfräuleins, die auf den immer sauber gescheuerten Fliesen der Küche so allerliebst schlürften und klapperten. In diesen Schuhen sah Emma viel größer aus denn sonst. Wenn Karl wieder ging, gab sie ihm jedesmal das Geleit bis zur ersten Stufe der Freitreppe. War sein Pferd noch nicht vorgeführt, dann wartete sie mit. Sie hatten schon Abschied voneinander genommen, und so sprachen sie nicht mehr. Wenn es sehr windig war, kam ihr flaumiges Haar im Nacken in wehenden Wirrwarr, oder die Schürzenbänder begannen ihr um die Hüften zu flattern. Einmal war Tauwetter. An den Rinden der Bäume rann Wasser in den Hof hinab, und auf den Dächern der Gebäude schmolz aller Schnee. Emma war bereits auf der Schwelle, da ging sie wieder ins Haus, holte ihren Sonnenschirm und spannte ihn auf. Die Sonnenlichter stahlen sich durch die taubengraue Seide und tupften tanzende Reflexe auf die weiße Haut ihres Gesichts. Das gab ein so warmes und wohliges Gefühl, daß Emma lächelte. Einzelne Wassertropfen prallten auf das Schirmdach, laut vernehmbar, einer, wieder einer, noch einer ...
        Im Anfang hatte Frau Bovary häufig nach Herrn Rouault und seiner Krankheit gefragt, auch hatte sie nicht verfehlt, für ihn in ihrer doppelten Buchführung ein besondres Konto einzurichten. Als sie aber vernahm, daß er eine Tochter hatte, zog sie nähere Erkundigungen ein, und da erfuhr sie, daß Fräulein Rouault im Kloster, bei den Ursulinerinnen, erzogen worden war, sozusagen also „eine feine Erziehung genossen“ hatte, daß sie infolgedessen Kenntnisse im Tanzen, in der Erdkunde, im Zeichnen, Sticken und Klavierspielen haben mußte. Das ging ihr über die Hutschnur, wie man zu sagen pflegt.
        „Also darum!“ sagte sie sich. „Darum also lacht ihm das ganze Gesicht, wenn er zu ihr hinreitet! Darum zieht er die neue Weste an, gleichgültig, ob sie ihm vom Regen verdorben wird! Oh dieses Weib, dieses Weib!“
        Instinktiv haßte sie Emma. Zuerst tat sie sich eine Güte in allerhand Anspielungen. Karl verstand das nicht. Darauf versuchte sie es mit anzüglichen Bemerkungen, die er aus Angst vor einer häuslichen Szene über sich ergehen ließ. Schließlich aber ging sie im Sturm vor. Karl wußte nicht, was er sagen sollte. Weshalb renne er denn ewig nach Bertaux, wo doch der Alte längst geheilt sei, wenn die Rasselbande auch noch nicht berappt habe? Na freilich, weil es da „eine Person“ gäbe, die fein zu schwatzen verstünde, ein Weibsbild, das sticken könne und weiter nichts, ein Blaustrumpf! In die sei er verschossen! Ein Stadtdämchen, das sei ihm ein gefundenes Fressen.
        „Blödsinn!“ polterte sie weiter. „Die Tochter des alten Rouault, die und eine feine Dame! O jeh! Ihr Großvater hat noch die Schafe gehütet, und ein Vetter von ihr ist beinahe vor den Staatsanwalt gekommen, weil er bei einem Streite jemanden halbtot gedroschen hat! So was hat gar keinen Anlaß, sich was Besonders einzubilden und Sonntags aufgedonnert in die Kirche zu schwänzeln, in seidnen Kleidern wie eine Prinzessin. Und der Alte, der arme Schluder! Wenn im vergangenen Jahre die Rapsernte nicht so unverschämt gut ausgefallen wäre, hätte er seinen lumpigen Pacht nicht mal blechen können!“
        Die Freude war Karl verdorben. Er stellte seine Ritte nach Bertaux ein. Seine Frau hatte ihn nach einer Flut von Tränen und Küssen und unter tausend Zärtlichkeiten auf ihr Meßbuch schwören lassen, nicht mehr hinzugehen. Er gehorchte. Aber in seiner heimlichen Sehnsucht war er kühner; da war er empört über seine tatsächliche eigne Feigheit. Und in naivem Machiavellismus sagte er sich, gerade ob dieses Verbots habe er ein Recht auf seine Liebe. Was war die ehemalige Witwe auch für ein Weib: sie war spindeldürr und hatte häßliche Zähne; Sommer wie Winter trug sie denselben schwarzen Schal mit dem über den Rücken herabhängenden langen Zipfel; ihre steife Figur stak in den immer zu kurzen Kleidern wie in einem Futteral, und was für plumpe Schuhe trug sie über ihren grauen Strümpfen.
        Karls Mutter kam von Zeit zu Zeit zu Besuch. Dann wurde es noch schlimmer; dann hackten sie alle beide auf ihn ein. Das viele Essen bekäme ihm schlecht. Warum er dem ersten besten immer gleich ein Glas Wein vorsetze? Und es sei bloß Dickköpfigkeit von ihm, keine Flanellwäsche zu tragen.
        Zu Beginn des Frühlings begab es sich, daß der Vermögensverwalter der Frau verwitweten Dubuc, ein Notar in Ingouville, samt allen ihm anvertrauten Geldern übers Meer das Weite suchte. Nun besaß sie allerdings außerdem einen Schiffsanteil in der Höhe von sechstausend Franken und ein Haus in Dieppe. Aber von allen diesen vielgepriesenen Besitztümern hatte man nie etwas Ordentliches zu sehen bekommen. Die Witwe hatte nichts mit in die Ehe gebracht als ein paar Möbel und etliche Nippsachen. Nunmehr ging man der Sache auf den Grund, und da stellte sich denn heraus, daß besagtes Haus bis an die Feueresse mit Hypotheken belastet, daß kein Mensch wußte, wieviel Geld wirklich mit dem Notar zum Teufel gegangen, und daß die Schiffshypothek keine tausend Taler wert war. Folglich hatte die liebe Frau Heloise geflunkert. In seinem Zorn warf der alte Bovary einen Stuhl gegen die Wand, daß er in tausend Stücke ging, und machte seiner Frau den Vorwurf, sie habe den Jungen in das Unglück gestürzt und ihn mit einer alten Kracke eingespannt, die des Futters nicht einmal mehr wert sei.
        Sie fuhren nach Tostes. Es kam zu einer Auseinandersetzung und zu heftigen Szenen. Heloise warf sich weinend in die Arme ihres Gatten und beschwor ihn, sie den Eltern gegenüber in Schutz zu nehmen. Karl wollte die Partei seiner Frau ergreifen. Aber das nahmen ihm die Alten übel. Sie reisten ab.
        Diesen Schlag vermochte Heloise nicht zu verwinden. Acht Tage darnach, als sie dabei war, Wäsche im Hofe aufzuhängen, bekam sie einen Blutsturz, und am andern Morgen war sie tot.
        Als Karl vom Friedhofe zurückkam, fand er im Erdgeschoß keinen Menschen. Er stieg die Treppe hinauf. Wie er in das Schlafzimmer trat, fiel sein Blick auf einen Rock Heloisens, der am Bette hing. Er lehnte sich gegen das Schreibpult und blieb da hocken, bis es dunkel wurde, in schmerzliche Träumereien versunken. Alles in allem hatte sie ihn doch geliebt ...
        Drittes Kapitel
        Eines Vormittags erschien Vater Rouault und brachte das Honorar für den behandelten Beinbruch: fünfundsiebzig Franken in blanken Talern und eine Truthenne. Er hatte Karls Unglück erfahren und tröstete ihn, so gut er konnte.
        „Ich weiß, wie einem da zumute ist!“ sagte er, indem er dem Witwer auf die Schulter klopfte. „Habs ja selber mal durchgemacht, ganz so wie Sie! Als ich meine Selige begraben hatte, da lief ich hinaus ins Freie, um allein für mich zu sein. Ich warf mich im Walde hin und weinte mich aus. Fing an, mit dem lieben Gott zu hadern, und machte ihm die dümmsten Vorwürfe. An einem Aste sah ich einen verreckten Maulwurf hängen, dem der Bauch von Würmern wimmelte. Ich beneidete den Kadaver! Und wenn ich daran dachte, daß im selben Augenblicke andre Männer mit ihren netten kleinen Frauen zusammen waren und sie an sich drückten, schlug ich mit meinem Stocke wild um mich. Es war sozusagen nicht mehr ganz richtig mit mir. Ich aß nicht mehr. Der bloße Gedanke, in ein Kaffeehaus zu gehn, ekelte mich an. Glauben Sie mir das! Na, und so nach und nach im Gang der Zeiten, wie so der Frühling dem Winter und der Herbst dem Sommer folgte, da gings eins, zwei, drei, und weg war der Jammer! Weg! Hinunter! Das ist das richtige Wort: hinunter! Denn ganz kriegt man ja so was im ganzen Leben nicht los. Da tief drinnen in der Brust bleibt immer was stecken. Aber Luft kriegt man wieder! Sehen Sie, das ist nun einmal unser aller Schicksal, und deshalb darf man nicht gleich die Flinte ins Korn werfen. Man darf nicht sterben wollen, weil andere gestorben sind. Auch Sie müssen sich aufrappeln, Herr Bovary! Es geht alles vorüber! Besuchen Sie uns! Sie wissen ja, meine Emma denkt oft an Sie. Sie hätten uns vergessen, meint sie. Es wird nun Frühling. Zerstreuen Sie sich ein bißchen bei uns. Schießen Sie ein paar Karnickel auf meinem Revier!“
        Karl befolgte seinen Rat. Er kam wieder nach Bertaux und fand da alles wie einst, das heißt wie vor fünf Monaten. Die Birnbäume hatten schon Blüten, und der treffliche Vater Rouault war wieder mordsgesund und von früh bis abend auf den Beinen. Und im ganzen Gut war mächtiger Betrieb.
        Es war ihm eine Ehrensache, den Arzt mit der erdenklichsten Rücksicht auf sein Leid zu behandeln. Er bat ihn, sichs so bequem wie nur möglich zu machen, sprach im Flüstertone mit ihm wie mit einem Genesenden, und er war sichtlich außer sich, wenn man des Gastes wegen nicht, wie befohlen, die leichtverdaulichsten Gerichte auf den Tisch brachte, zum Beispiel feine Eierspeisen oder gedünstete Birnen. Er erzählte Anekdoten und Abenteuer. Zu seiner eignen Verwunderung lachte Karl. Aber mir einem Male erinnerte er sich seiner Frau und wurde nachdenklich. Der Kaffee ward gebracht, und da vergaß er sie wieder.
        Je mehr er sich an sein Witwertum gewöhnte, um so weniger gedachte er der Verstorbenen. Das angenehme, ihm neue Bewußtsein, unabhängig zu sein, machte ihm die Einsamkeit bald erträglicher. Jetzt durfte er die Stunden der Mahlzeiten selber bestimmen, konnte gehen und kommen, ohne Rechenschaft darüber geben zu müssen, und wenn er müde war, alle vier von sich strecken und sich in seinem Bette breit machen. Er hegte und pflegte sich und ließ alle Tröstungen über sich ergehen. Übrigens hatte der Tod seiner Frau keine ungünstige Wirkung auf seinen Beruf als Arzt. Indem man wochenlang in einem fort sagte: „Der arme Doktor. Wie traurig!“ blieb sein Name im Munde der Leute. Seine Praxis vergrößerte sich. Und dann konnte er nun nach Bertaux reiten, wann es ihm beliebte. Eine unbestimmbare Sehnsucht wuchs in ihm auf, ein namenloses Glücksgefühl. Wenn er sich im Spiegel betrachtete und sich den Bart strich, fand er sich gar nicht übel.
        Eines schönen Tages kam er nachmittags gegen drei Uhr im Gute angeritten. Alles war draußen auf dem Felde. Er betrat die Küche. Emma war drinnen, aber er bemerkte sie zunächst nicht. Die Fensterläden waren geschlossen. Durch die Ritzen des Holzes stachen die Sonnenstrahlen mit langen dünnen Nadeln auf die Fliesen, oder sie brachen sich an den Kanten der Möbel entzwei und wirbelten hinauf zur Decke. Auf dem Küchentische krabbelten Fliegen an den Gläsern hinauf, purzelten summend in die Apfelweinneigen und ertranken. Das Sonnenlicht, das durch den Kamin eindrang, verwandelte die rußige Herdplatte in eine Samtfläche und färbte den Aschehaufen blau. Emma saß zwischen dem Fenster und dem Herd und nähte. Sie hatte kein Halstuch um, und auf ihren entblößten Schultern glänzten kleine Schweißperlen.
        Nach ländlichem Brauch bot sie dem Ankömmling einen Trunk an. Als er ihn ausschlug, nötigte sie ihn, und schließlich bat sie ihn lachend, ein Gläschen Likör mit ihr zu trinken. Sie holte aus dem Schranke eine Flasche Curaçao, suchte zwei Gläser heraus, füllte das eine bis zum Rande und goß in das andre ein paar Tropfen. Sie stieß mit Karl an und führte dann ihr Glas zum Munde. Da soviel wie nichts drin war, mußte sie sich beim Trinken zurückbiegen. Den Kopf nach hinten gelegt, die Lippen zugespitzt, den Hals gestrafft, so stand sie da und lachte darüber, daß ihr nichts auf die Zunge lief, obgleich diese mit der Spitze aus den feinen Zähnen herausspazierte und bis an den Boden des Glases mehreremals suchend vorstieß.
        Emma nahm wieder Platz und begann sich von neuem ihrer Handarbeit zu widmen. Ein weißer baumwollener Strumpf war zu stopfen. Mit gesenkter Stirn saß sie da. Sie sagte nichts und Karl erst recht nichts. Der Luftzug, der sich zwischen Tür und Schwelle eindrängte, wirbelte ein wenig Staub von den Fliesen auf. Karl sah diesem Tanze der Atome zu. Dabei hörte er nichts als das Hämmern seines Blutes im eignen Hirne und aus der Ferne das Gackern einer Henne, die irgendwo im Hofe ein Ei gelegt hatte. Hin und wieder hielt Emma die Handflächen ihrer Hände auf den kalten Knauf der Herdstange und preßte sie dann an ihre Wangen, um diese zu kühlen.
        Sie klagte über die Schwindelanfälle, von denen sie seit Frühjahrsanfang heimgesucht wurde, und fragte, ob ihr wohl Seebäder dienlich wären. Dann plauderte sie von ihrem Aufenthalt im Kloster und er von seiner Gymnasiastenzeit. So gerieten sie in ein Gespräch. Sie führte ihn in ihr Zimmer und zeigte ihm ihre Notenhefte von damals und die niedlichen Bücher, die sie als Schulprämien bekommen hatte, und die Eichenlaubkränze, die im untersten Schrankfache ihr Dasein fristeten. Dann erzählte sie von ihrer Mutter, von deren Grabe, und zeigte ihm sogar im Garten das Beet, wo die Blumen wüchsen, die sie der Toten jeden ersten Freitag im Monat hintrug. Der Gärtner, den sie hatten, verstünde nichts. Mit dem seien sie schlecht dran. Ihr Wunsch wäre es, wenigstens während der Wintermonate in der Stadt zu wohnen. Dann aber meinte sie wieder, an den langen Sommertagen sei das Leben auf dem Lande noch langweiliger. Und je nachdem, was sie sagte, klang ihre Stimme hell oder scharf; oder sie nahm plötzlich einen matten Ton an, und wenn sie wie mit sich selbst plauderte, ward sie wieder ganz anders, wie flüsternd und murmelnd. Bald war Emma lustig und hatte große unschuldige Augen, dann wieder schlossen sich ihre Lider zur Hälfte, und ihr schimmernder Blick sah teilnahmslos und traumverloren aus.
        Abends auf dem Heimritt wiederholte sich Karl alles, was sie geredet hatte, bis ins einzelne, und versuchte den vollen Sinn ihrer Worte zu erfassen. Er wollte sich damit eine Vorstellung von der Existenz schaffen, die Emma geführt, ehe er sie kennen gelernt hatte. Aber es gelang ihm nicht, sie in seinen Gedanken anders zu erschauen als so, wie sie ausgesehen hatte, als er sie zum ersten Male erblickt, oder so, wie er sie eben vor sich gehabt hatte. Dann fragte er sich, wie es wohl würde, wenn sie sich verheiratete, aber mit wem? Ja, ja, mit wem? Ihr Vater war so reich und sie ... so schön!
        Und immer wieder sah er Emmas Gesicht vor seinen geistigen Augen, und eine Art eintönige Melodie summte ihm durch die Ohren wie das Surren eines Kreisels: „Emma, wenn du dich verheiratetest! Wenn du dich nun verheiratetest!“ In der Nacht konnte er keinen Schlaf finden. Die Kehle war ihm wie zugeschnürt. Er verspürte Durst, stand auf, trank ein Glas Wasser und machte das Fenster auf. Der Himmel stand voller Sterne. Der laue Nachtwind strich in das Zimmer. Fern bellten Hunde. Er wandte den Blick in die Rötung nach Bertaux.
        Endlich kam er auf den Gedanken, daß es den Hals nicht kosten könne, und so nahm er sich vor, bei der ersten besten Gelegenheit um Emmas Hand zu bitten. Aber sooft sich diese Gelegenheit bot, wollten ihm vor lauter Angst die passenden Worte nicht über die Lippen. Vater Rouault hätte längst nichts dagegen gehabt, wenn ihm jemand seine Tochter geholt hätte. Im Grunde nützte sie ihm in Haus und Hof nicht viel. Er machte ihr keinen Vorwurf daraus: sie war eben für die Landwirtschaft zu geweckt. „Ein gottverdammtes Gewerbe!“ pflegte er zu schimpfen. „Das hat auch noch keinen zum Millionär gemacht!“ Ihm hatte es in der Tat keine Reichtümer gebracht; im Gegenteil, er setzte alle Jahre zu. Denn wenn er auch auf den Märkten zu seinem Stolz als gerissener Kerl bekannt war, so war er eigentlich doch für Ackerbau und Viehzucht durchaus nicht geschaffen. Er verstand nicht zu wirtschaften. Er nahm nicht gern die Hände aus den Hosentaschen, und seinem eigenen Leibe war er kein Stiefvater. Er hielt auf gut Essen und Trinken, einen warmen Ofen und ausgiebigen Schlaf. Ein gutes Glas Landwein, ein halb durchgebratenes Hammelkotelett und ein Täßchen Mokka mit Kognak gehörten zu den Idealen seines Lebens. Er nahm seine Mahlzeiten in der Küche ein und zwar allein für sich, in der Nähe des Herdfeuers an einem kleinen Tische, der ihm — wie auf der Bühne — fix und fertig gedeckt hereingebracht werden mußte.
        Als er die Entdeckung machte, daß Karl einen roten Kopf bekam, wenn er Emma sah, war er sich sofort klar, daß früher oder später ein Heiratsantrag zu erwarten war. Alsobald überlegte er sich die Geschichte. Besonders schneidig sah ja Karl Bovary nicht gerade aus, und Rouault hatte sich ehedem seinen künftigen Schwiegersohn ein bißchen anders gedacht, aber er war doch als anständiger Kerl bekannt, sparsam und tüchtig in seinem Berufe. Und zweifellos würde er wegen der Mitgift nicht lange feilschen. Vater Rouault hatte gerade eine Menge großer Ausgaben. Um allerlei Handwerker zu bezahlen, sah er sich gezwungen, zweiundzwanzig Acker von seinem Grund und Boden zu verkaufen. Die Kelter mußte auch erneuert werden. Und so sagte er sich: „Wenn er um Emma anhält, soll er sie kriegen!“
        Zur Weinlese war Karl drei Tage lang da. Aber Tag verging auf Tag und Stunde auf Stunde, ohne daß Karls Wille zur Tat ward. Rouault gab ihm ein kleines Stück Wegs das Geleite; am Ende des Hohlwegs vor dem Dorfe pflegte er sich von seinem Gaste zu verabschieden. Das war also der Moment! Karl nahm sich noch Zeit bis zuallerletzt. Erst als die Hecke hinter ihnen lag, stotterte er los:
        „Verehrter Herr Rouault, ich möchte Ihnen gern etwas sagen!“
        Weiter brachte er nichts heraus. Die beiden Männer blieben stehen.
        „Na, raus mit der Sprache! Ich kann mirs schon denken!“ Rouault lachte gemütlich.
        „Vater Rouault! Vater Rouault!“ stammelte Karl.
        „Meinen Segen sollen Sie haben!“ fuhr der Gut-späch-ter fort. „Meine Kleine denkt gewiß nicht anders als ich, aber gefragt werden muß sie. Reiten Sie getrost nach Hause. Ich werde sie gleich mal ins Gebet nehmen. Wenn sie Ja sagt, — wohlverstanden! — brauchen Sie jedoch nicht umzukehren. Wegen der Leute nicht, und auch weil sie sich erst ein bißchen beruhigen soll. Damit Sie aber nicht zu lange Blut schwitzen, will ich Ihnen ein Zeichen geben: ich werde einen Fensterladen gegen die Mauer klappen lassen. Wenn Sie da oben über die Hecke gucken, können Sie das ungesehen beobachten!“
        Damit ging er.
        Karl band seinen Schimmel an einen Baum; kletterte die Böschung hinauf und stellt sich auf die Lauer, die Taschenuhr in der Hand. Eine halbe Stunde verstrich — und dann noch neunzehn Minuten ... Da gab es mit einem Male einen Schlag gegen die Mauer. Der Laden blieb sperrangelweit offen und wackelte noch eine Weile.
        Am andern Morgen war Karl vor neun Uhr in Bertaux. Emma wurde über und über rot, als sie ihn sah. Sie lächelte gezwungen ein wenig, um ihre Fassung zu bewahren. Rouault umarmte seinen künftigen Schwiegersohn. Die Besprechung der geschäftlichen Punkte wurde verschoben. Übrigens war noch viel Zeit dazu, da die Hochzeit anstandshalber vor Ablauf von Karls Trauerjahr nicht stattfinden konnte, das hieß, nicht vor dem nächsten Frühjahr.
        In dieser Erwartung verging der Winter. Fräulein Rouault beschäftigte sich mit ihrer Aussteuer. Ein Teil davon wurde in Rouen bestellt. Die Hemden und Hauben stellte sie nach Schnitten, die sie sich lieh, selbst her. Wenn Karl zu Besuch kam, plauderte das Brautpaar von den Vorbereitungen zur Hochzeitsfeier. Es wurde überlegt, in welchem Raume das Festmahl stattfinden, wieviel Platten und Schüsseln auf die Tafel kommen und was für Vorspeisen es geben solle.
        Am liebsten hätte es Emma gehabt, wenn die Trauung auf nachts zwölf Uhr bei Fackelschein festgesetzt worden wäre; aber für solche Romantik hatte Vater Rouault kein Verständnis. Man einigte sich also auf eine Hochzeitsfeier, zu der dreiundvierzig Gäste Einladungen bekamen. Sechzehn Stunden wollte man bei Tisch sitzen bleiben. Am nächsten Tage und an den folgenden sollte es so weitergehen.
        Viertes Kapitel
        Die Hochzeitsgäste stellten sich pünktlich ein, in Kutschen, Landauern, Einspännern, Gigs, Kremsern mit Ledervorhängen, in allerlei Fuhrwerk moderner und vorsintflutlicher Art. Das junge Volk aus den nächsten Nachbardörfern kam tüchtig durchgerüttelt im Trabe in einem Heuwagen angefahren, aufrecht in einer Reihe stehend, die Hände an den Seitenstangen, um nicht umzufallen. Etliche eilten zehn Wegstunden weit herbei, aus Goderville, Normanville und Cany. Die Verwandten beider Familien waren samt und sonders geladen. Freunde, mit denen man uneins gewesen, versöhnte man, und es war an Bekannte geschrieben worden, von denen man wer weiß wie lange nichts gehört hatte.
        Immer wieder vernahm man hinter der Gartenhecke Peitschengeknall. Eine Weile später erschien der Wagen im Hoftor. Im Galopp ging es bis zur Freitreppe, wo mit einem Rucke gehalten wurde. Die Insassen stiegen nach beiden Seiten aus. Man rieb sich die Knie und turnte mit den Armen. Die Damen, Hauben auf dem Kopfe, trugen städtische Kleider, goldne Uhrketten, Umhänge mit langen Enden, die sie sich kreuzweise umgeschlagen hatten, oder Schals, die mit einer Nadel auf dem Rücken festgesteckt waren, damit sie hinten den Hals frei ließen. Die Knaben, genau so angezogen wie ihre Väter, fühlten sich in ihren Röcken sichtlich unbehaglich; viele hatten an diesem Tage gar zum ersten Male richtige Stiefel an. Ihnen Dzünschten ihm ungeniert alles Üble. der witzenheimer zur Seite gewahrte man vierzehn- bis sechzehnjährige Mädchen, offenbar ihre Basen oder älteren Schwestern, in ihren weißen Firmelkleidern, die man zur Feier des Tages um ein Stück länger gemacht hatte, alle mit roten verschämten Gesichtern und pomadisiertem Haar, voller Angst, sich die Handschuhe nicht zu beschmutzen. Da nicht Knechte genug da waren, um all die Wagen gleichzeitig abzuspannen, streiften die Herren die Rockärmel hoch und stellten ihre Pferde eigenhändig ein. Je nach ihrem gesellschaftlichen Range waren sie in Fräcken, Röcken oder Jacketts erschienen. Manche in ehrwürdigen Bratenröcken, die nur bei ganz besonderen Festlichkeiten feierlich aus dem Schranke geholt wurden; ihre langen Schöße flatterten im Winde, die Kragen daran sahen aus wie Halspanzer, und die Taschen hatten den Umfang von Säcken. Es waren auch Jacken aus derbem Tuch zum Vorschein gekommen, meist im Verein mit messingumränderten Mützen; fernerhin ganz kurze Röcke mit zwei dicht nebeneinandersitzenden großen Knöpfen hinten in der Taille und mit Schößen, die so ausschauten, als habe sie der Zimmermann mit einem Beile aus dem Ganzen herausgehackt. Ein paar (einige wenige) Gäste — und das waren solche, die dann an der Festtafel gewiß am alleruntersten Ende zu sitzen kamen — trugen nur Sonntagsblusen mit breitem Umlegekragen und Rückenfalten unter dem Gürtel.
        Die steifen Hemden wölbten sich über den Brüsten wie Kürasse. Durchweg hatte man sich unlängst das Haar schneiden lassen (um so mehr standen die Ohren von den Schädeln ab!), und alle waren ordentlich rasiert. Manche, die noch im Dunkeln aufgestanden waren, hatten offenbar beim Rasieren nicht Licht genug gehabt und hatten sich unter der Nase die Kreuz und die Quer geschnitten oder hatten am Kinn Löcher in der Haut bekommen, groß wie Talerstücke. Unterwegs hatten sich diese Wunden in der frischen Morgenluft gerötet, und so leuchteten auf den breiten blassen Bauerngesichtern große rote Flecke.
        Das Gemeindeamt lag eine halbe Stunde vom Pachthofe entfernt. Man begab sich zu Fuß dahin und ebenso zurück, nachdem die Zeremonie in der Kirche stattgefunden hatte. Der Hochzeitszug war anfangs wohlgeordnet gewesen. Wie ein buntes Band hatte er sich durch die grünen Felder geschlängelt. Aber bald lockerte er sich und zerfiel in verschiedene Gruppen, von denen sich die letzten plaudernd verspäteten. Ganz vorn schritt ein Spielmann mit einer buntbebänderten Fiedel. Dann kamen die Brautleute, darauf die Verwandten, dahinter ohne besondre Ordnung die Freunde und zuletzt die Kinder, die sich damit vergnügten, Ähren aus den Kornfeldern zu rupfen oder sich zu jagen, wenn es niemand sah. Emmas Kleid, das etwas zu lang war, schleppte ein wenig auf der Erde hin. Von Zeit zu Zeit blieb sie stehen, um den Rock aufzuraffen. Dabei las sie behutsam mit ihren behandschuhten Händen die kleinen stacheligen Distelblätter ab, die an ihrem Kleide hängen geblieben waren. Währenddem stand Karl mit leeren Händen da und wartete, bis sie fertig war. Vater Rouault trug einen neuen Zylinderhut und einen schwarzen Rock, dessen Ärmel ihm bis an die Fingernägel reichten. Am Arm führte er Frau Bovary senior. Der alte Herr Bovary, der im Grunde seines Herzens die ganze Sippschaft um sich herum verachtete, war einfach in einem uniformähnlichen einreihigen Rock erschienen. Ihm zur Seite schritt eine junge blonde Bäuerin, die er mir derben Galanterien traktierte. Sie hörte ihm respektvoll zu, wußte aber in ihrer Verlegenheit gar nicht, was sie sagen sollte. Die übrigen Gäste sprachen von ihren Geschäften oder ulkten sich gegenseitig an, um sich in fidele Stimmung zu bringen. Wer aufhorchte, hörte in einem fort das Tirilieren des Spielmannes, der auch im freien Felde weitergeigte. Sooft er bemerkte, daß die Gesellschaft weit hinter ihm zurückgeblieben war, machte er Halt und schöpfte Atem. Umständlich rieb er seinen Fiedelbogen mit Kolophonium ein, damit die Saiten schöner quietschen sollten, und dann setzte er sich wieder in Bewegung. Er hob und senkte den Hals seines Instruments, um recht hübsch im Takte zu bleiben. Die Fidelei verscheuchte die Vögel schon von weitem.
        Die Festtafel war unter dem Schutzdache des Wagenschuppens aufgestellt. Es prangten darauf vier Lendenbraten, sechs Schüsseln mit Hühnerfrikassee, eine Platte mit gekochtem Kalbfleisch, drei Hammelkeulen Dzünschten ihm ungeniert alles Üble. der witzenheimer und in der Mitte, umgeben von vier Leberwürsten in Sauerkraut, ein köstlich knusprig gebratenes Spanferkel. An den vier Ecken des Tisches brüsteten sich Karaffen mit Branntwein, und in einer langen Reihe von Flaschen wirbelte perlender Apfelweinsekt, während auf der Tafel bereits alle Gläser im voraus bis an den Rand vollgeschenkt waren. Große Teller mit gelber Creme, die beim leisesten Stoß gegen den Tisch zitterte und bebte, vervollständigten die Augenweide. Auf der glatten Oberfläche dieses Desserts prangten in umschnörkelten Monogrammen von Zuckerguß die Anfangsbuchstaben der Namen von Braut und Bräutigam. Für die Torten und Kuchen hatte man einen Konditor aus Yvetot kommen lassen. Da dies sein Debüt in der Gegend war, hatte er sich ganz besondre Mühe gegeben. Beim Nachtisch trug er eigenhändig ein Prunkstück seiner Kunst auf, das ein allgemeines „Ah!“ hervorrief. Der Unterbau aus blauer Pappe stellte ein von Sternen aus Goldpapier übersätes Tempelchen dar, mit einem Säulenumgang und Nischen, in denen Statuen aus Marzipan standen. Im zweiten Stockwerk rundete sich ein Festungsturm aus Pfefferkuchen, umbaut von einer Brustwehr aus Bonbons, Mandeln, Rosinen und Apfelsinenschnitten. Die oberste Plattform aber krönte über einer grünen Landschaft aus Wiesen, Felsen und Teichen mit Nußschalenschiffchen darauf (alles Zuckerwerk): ein niedlicher Amor, der sich auf einer Schaukel aus Schokolade wiegte. In den beiden kugelgeschmückten Schnäbeln der Schaukel steckten zwei lebendige Rosenknospen.
        Man schmauste bis zum Abend. Wer von dem zu langen Sitzen ermüdet war, ging im Hof oder im Garten spazieren oder machte eine Partie des in jener Gegend beliebten Pfropfenspiels mit und setzte sich dann wieder an den Tisch. Ein paar Gäste schliefen gegen das Ende des Mahles ein und schnarchten ganz laut. Aber beim Kaffee war alles wieder munter. Man sang Lieder, vollführte allerlei Kraftleistungen, stemmte schwere Steine, schoß Purzelbäume, hob Schubkarren bis zur Schulterhöhe, erzählte gepfefferte Geschichten und scharwenzelte mit den Damen.
        Vor dem Aufbruch war es kein leichtes Stück Arbeit, den Pfer~den, die allesamt der allzu reichlich vertilgte Hafer stach, die Kumte und Geschirre aufzulegen. Die übermütigen Tiere stiegen, bockten und schlugen aus, während die Herren und Kutscher fluchten und lachten. Die ganze Nacht hindurch gab es auf den mondbeglänzten Landstraßen in Karriere über Stock und Stein heimrasende Fuhrwerke.
        Die nachtüber in Bertaux bleibenden Gäste zechten am Küchentische bis zum frühen Morgen weiter, während die Kinder unter den Bänken schliefen.
        Die junge Frau hatte ihren Vater besonders gebeten, sie vor den herkömmlichen Späßen zu bewahren. Indessen machte sich ein Vetter — ein Seefischhändler, der als Hochzeitsgeschenk selbstverständlich ein paar Seezungen gestiftet hatte — doch daran, einen Mund voll Wasser durch das Schlüsselloch des Brautgemachs zu spritzen. Vater Rouault erwischte ihn gerade noch rechtzeitig, um ihn daran zu hindern. Er machte ihm klar, daß sich derartige Scherze mit der Würde seines Schwiegersohnes nicht vertrügen. Der Vetter ließ sich durch diese Einwände nur widerwillig von seinem Vorhaben abbringen. Insgeheim hielt er den alten Rouault für aufgeblasen. Er setzte sich unten in eine Ecke mir vier bis fünf andern Unzufriedenen, die während des Mahles bei der Wahl der Fleischstücke Mißgriffe getan hatten. Diese Unglücksmenschen räsonierten nun alle untereinander auf den Gastgeber und Dzüns-chten ihm ungeniert alles Üble . der witzenheimer');

    SELECT 
        UNNEST(ARRAY[
        IS(ts_semantic_headline('german', content, PHRASETO_TSQUERY('german', 'Dzünschten ihm ungeniert alles Üble')), 
        '<b>Dzünschten ihm ungeniert alles Üble.</b> der witzenheimer zur Seite gewahrte man vierzehn- bis sechzehnjährige Mädchen', 
        'German Test 1: Seeking `Dzünschten ihm ungeniert alles Üble`'), 
        
        IS(ts_semantic_headline('german', content, PHRASETO_TSQUERY('german', 'Schutzdache des Wagenschuppens aufgestellt')), 
        '<b>Schutzdache des Wagenschuppens aufgestellt.</b> Es prangten darauf vier Lendenbraten, sechs Schüsseln mit Hühnerfrikassee, eine Platte', 
        'German Test 2: Seeking `Schutzdache des Wagenschuppens aufgestellt`'),

        IS(ts_semantic_headline('german', content, PHRASETO_TSQUERY('german', 'bleibenden Gäste zecht')), 
        '<b>bleibenden Gäste zechten</b> am Küchentische bis zum frühen Morgen weiter, während die Kinder unter den Bänken', 
        'German Test 3; Seeking: bleibenden Gäste zecht`'),

        IS(ts_semantic_headline('german', content, PHRASETO_TSQUERY('german', 'Kutschen, Landauern, Einspännern')), 
        '<b>Kutschen, Landauern, Einspännern,</b> Gigs, Kremsern mit Ledervorhängen, in allerlei Fuhrwerk moderner und vorsintflutlicher Art. Das junge', 
        'German Test 4; Seeking: Kutschen, Landauern, Einspännern`'),
        
        IS(ts_semantic_headline('german', content, PHRASETO_TSQUERY('german', 'Hochzeitsgeschenk')), 
        '<b>Hochzeitsgeschenk</b> selbstverständlich ein paar Seezungen gestiftet hatte doch daran, einen Mund voll Wasser durch', 
        'German Test 5; Seeking: Hochzeitsgeschenk`')

        ]) AS ts_semantic_headline_assertions

    FROM _files;

-- End the test
ROLLBACK;


